name: deploy-dev

on:
  push:
    branches: ["deploy-dev"]

  workflow_dispatch:

jobs:
  build:
    runs-on: ["self-hosted"]

    steps:
      - uses: actions/checkout@v2

      - name: Pull the change from server
        run: | 
          git pull origin deploy-dev --rebase